workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1                                                                                                                                                                                                                  
publishing:
  email:
    recipients:
      - davidjohnson297@yahoo.com
      - davidjohnson4648@aol.com
    notify:
      success: true
      failure: false 