workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
artifacts:
  - build/**/outputs/**/*.app
  - build/**/outputs/**/mapping.txt
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - flutter_drive.log
publishing:
  email:
    recipients:
      - davidjohnson297@yahoo.com
    notify:
      success: true
      failure: true 